#!/bin/sh
# Adds libokFrontPanel.so and okimpl_fpoip.so to $LD_LIBRARY_PATH
# Before launching FrontPanel.bin
bindir="$(dirname $(readlink -f $0))"

if [ -d "$bindir/../lib" ]; then # Points to the lib folder where the .so files were copied in the installer
    LD_LIBRARY_PATH="$bindir/../lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" 
    export LD_LIBRARY_PATH
elif [ -d "$bindir/API" ]; then # Points to the API folder in the downloaded FrontPanel folder
    LD_LIBRARY_PATH="$bindir/API${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" 
    export LD_LIBRARY_PATH
else
    echo "Warning: could not find the directory containing libokFrontPanel.so (checked $(realpath -f $bindir/../lib) and $(realpath -f $bindir/API)."
fi
        
exec $bindir/FrontPanel.bin "$@"
